### ISSUE TITLE
About README remark about Chevereto API

### ISSUE THREAD

**Issue by rodber** [M1Screw/Chevereto-Telegram-Bot#92]
Hi, at your GitHub user profile you have this bit:

>  It currently only supports uploading images as an anonymous user due to Chevereto's API limitation, but after its per-user API system is released, I plan to refactor this simple bot to a more feature-rich & easier-to-use state.

Chevereto has supported user-based API upload since 2022, here: https://releases.chevereto.com/4.X/4.0/4.0.0.html note at the documentation: https://v4-docs.chevereto.com/developer/api/api-v1.html#key

```plain
API V1.1 works with a user key which is available for each user at /settings/api. Admin user can set the public API key for guest uploads at the Dashboard panel.
```

There's no change required at your end either, it is just a different API key so simply fix the instructions.

Hope it helps!

**Comment by M1Screw** [comment]
Thank you for the advice! I haven't read the API doc in a long time, and I thought the per-user API wouldn't come out until API v4 is GA. 

For the project itself though, this project is intended for site owners who want to run a telegram bot for their image-hosting site. Sure users can run a local instance of the bot, but that won't be ideal.

It requires a significant rewrite of how the authorization works and adding a storage backend for the user's telegram ID and their API token to make the true multi-user mode work, and that's what I am planning to do when API v4 comes out.

Looking forward to the update, cheers.
